### ISSUE TITLE
Investigate if we are legally allowed to use Google's pacman resources

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#11]
I mean these sprites:
![](http://www.google.com/logos/pacman10-hp-sprite.png)

**Comment by rexim** [comment]
They are from this doodle https://www.google.com/doodles/30th-anniversary-of-pac-man

**Comment by rexim** [comment]
http://www.google.com/permissions/using-the-logo.html

### Google Doodles

> Our Doodles (illustrated logos) are featured throughout the year on our homepage. We've created a gallery where you can enjoy them, but we generally don’t grant permission for their use by others. We also do not grant permission for users to create and publish their own versions of the Google logo.

**Comment by rexim** [comment]
But we are not going to use the whole doodle. We are going to use only the sprite sheet. And for this case I cannot find anything.

@ForNeVeR, @Minoru, what do you guys think?

**Comment by Minoru** [comment]
These terms are vague, and the fact that you can interpret them the way that suits your goals doesn't mean Google's lawyers will do so, too. Realistically, I don't think they'll sue you, but legally, I'd advise against using those.

I looked for other sprites, but without much luck (i.e. they're all in the same "grey zone" as Google's). How much work will it take to draw your own?

**Comment by rexim** [comment]
@Minoru, thank you very much for taking a look into this!

> How much work will it take to draw your own?

Don't think it's too hard. I'll try to draw them before the next stream. ;)

**Comment by ForNeVeR** [comment]
Regarding your initial question - I think that's pretty clear that we cannot use any part of the doodle in any purpose inside our products. The fact that they maybe haven't told that in the disclaimer means nothing. If the license haven't explicitly permitted our use - it is forbidden. That's the way software and artistic licensing generally work.

**Comment by rexim** [comment]
@ForNeVeR wow! Didn't know those details! Thank you!
