### ISSUE TITLE
args-out-of-range error on M-x pacmacs-start

### ISSUE THREAD

**Issue by kaushalmodi** [codingteam/pacmacs.el#116]
Hi,

I was intrigued to try this package when I saw it pop up as a new package in the the package manager.

But I am unable to run it.

On doing `M-x pacmacs-start`, I get

```
Debugger entered--Lisp error: (args-out-of-range "." 362 388)
  match-string(1 ".")
  pacmacs--levelname-from-filename(".")
  mapcar(pacmacs--levelname-from-filename ("." ".." "game-over.txt" "map01.txt" "map02.txt" "map03.txt" "map04.txt" "map05.txt" "map06.txt"))
  -map(pacmacs--levelname-from-filename ("." ".." "game-over.txt" "map01.txt" "map02.txt" "map03.txt" "map04.txt" "map05.txt" "map06.txt"))
  pacmacs--get-list-of-levels()
  pacmacs-start()
  funcall-interactively(pacmacs-start)
  call-interactively(pacmacs-start record nil)
  command-execute(pacmacs-start record)
```

I am running the latest version of GNU Emacs built from trunk (version 25.x).

**Comment by rexim** [comment]
Hello @kaushalmodi!

Thank you very much for you report. We already fixed that in 0c0aee723a79917962c24260beb1fc0ba31a6899 and all you need to do is just to wait until MELPA updates. :)

Also I usually stream on how I develop this game: https://www.livecoding.tv/rexim/ And we found this bug right on the stream and fixed it there a couple of hours ago. :)

**Comment by rexim** [comment]
@kaushalmodi and if you will continue to experience this error even after the MELPA update, please let us know. Thanks!

**Comment by kaushalmodi** [comment]
Thanks! It's fixed now :)

**Comment by rexim** [comment]
@kaushalmodi I'm so glad to hear that! Please, enjoy the game! :)

We will continue to develop it and there will be much more features in the future. Please stay tuned. ;)
