### ISSUE TITLE
Please add this animation in the README

### ISSUE THREAD

**Issue by ReneFroger** [codingteam/pacmacs.el#118]
From: https://www.reddit.com/r/emacs/comments/3opb5k/pacmacs_a_pacman_variant_for_emacs/ 

![tq7kcc7](https://cloud.githubusercontent.com/assets/5211845/10491579/9ba466b2-72a7-11e5-982c-579ed6abe1a5.gif)

**Comment by ForNeVeR** [comment]
Thank you for the issue!
