### ISSUE TITLE
Slow object look up

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#126]

**Comment by ForNeVeR** [comment]
What's the issue here? Do you want to look up poor object or simply apologize about some poor object?

**Comment by rexim** [comment]
@ForNeVeR I didn't finish here. Just reported a ticket to not forget to elaborate on that.

**Comment by rexim** [comment]
@ForNeVeR now we are looking up for slow objects

**Comment by ForNeVeR** [comment]
Well, that shouldn't cause too much of trouble. After all, they are slow. How far can they get? We'll look them up easily!
