### ISSUE TITLE
Wall sprites

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/pacmacs.el#131]
The wall sprites was more detailed in the original game. I think it will be worth to draw some sprites for them in pacmacs.

There should be 14 wall sprites overall if I was not mistaken (for various wall connection variants). Also you should implement a sprite selection logic for drawing the wall.

The following picture should render all of the walls with different sprites:

```
##

###  #
###  #
###

#
```

It will dramatically improve the game atmosphere.

**Comment by rexim** [comment]
It's actually really easy to do using xbm pixel-level access without drawing any sprites manually:

![Dramatically improved atmosphere](http://i.imgur.com/JuwyQiX.png)

But it's not that easy on Windows because of this bug #59 I think we have to investigate it further.

**Comment by rexim** [comment]
Once we have finished this, we need to make another animation video for the README
