### ISSUE TITLE
Update the animation in the README

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#137]
The current one is not relevant after #131 :)

**Comment by rexim** [comment]
http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast

**Comment by rexim** [comment]
@ForNeVeR you said you can try to record the animation on your powerful machine. Don't you mind to be assigned on this issue?

**Comment by rexim** [comment]
@ForNeVeR just added a couple of screenshots in 61b07fd6696a2d85402b81a2958a327acbe76094 until this issue is resolved and realized that they look really good on the front page of the project (especially with the GitHub Dark theme). Maybe we will stick with the screenshots from now on? They are much easier to make than an animation, PNGs have much better quality then GIFs. 

What do you think? Don't you mind to close this issue? Or maybe you still want to make an animation?

**Comment by ForNeVeR** [comment]
Well, I've looked at these screenshots and I think they are descriptive enough.

**Comment by rexim** [comment]
Thanks Mr @ForNeVeR! =3
