### ISSUE TITLE
Add glow to the walls

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/pacmacs.el#138]
I wanted to make this.

**Comment by rexim** [comment]
It could be difficult to do that with only one color for drawing walls, because of monochromness of XBM. :) But we can try to replace it with XPM then.

**Comment by ForNeVeR** [comment]
Good that you mentioned that. Okay, I'll see what we can do here.

**Comment by rexim** [comment]
Now we draw walls on XPM which supports much more colors than XBM %)

**Comment by rexim** [comment]
https://en.wikipedia.org/wiki/Dither

**Comment by rexim** [comment]
https://en.wikipedia.org/wiki/Kernel_(image_processing)
