### ISSUE TITLE
Walls are wrong on Windows

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/pacmacs.el#139]
I have tried both the version from the `master` branch directly and the version from melpa: in both of them I see something strange instead of the brand new walls.

![image](https://cloud.githubusercontent.com/assets/92793/10867222/bfc0ca9a-8080-11e5-92cd-6fef4be37301.png)

This **may** be my configuration issue, but I suggest further investigation. I am using the vanilla emacs that had no problems with pacmacs earlier.

This problem currently stops me from working on issue #137.

**Comment by rexim** [comment]
I'll take a look!

**Comment by rexim** [comment]
Dang it! I know what's wrong... I'm such an idiot! Let me fix that. :)

**Comment by rexim** [comment]
Basically, it's a regression of #59 I think we need a label for such things...

**Comment by rexim** [comment]
XBM support on Windows is so fucking broken! I think I can workaround all of the problems I currently facing, but if we will have more in the future I'll drop the XBM support immediately!

**Comment by rexim** [comment]
Well, maybe due to #138 we will drop it much sooner. %)

**Comment by rexim** [comment]
I can't workaround them. Dropping that shit.

**Comment by rexim** [comment]
Blocked by #141

**Comment by rexim** [comment]
Fixed in 528ca62e2810f8c23bb8b812c24a575df2bf3f2c

**Comment by rexim** [comment]
Verified on MELPA Pacmacs 20151102.1138, Windows 8.1, official Emacs build 24.5. Everything works well.
