### ISSUE TITLE
Video archive

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/pacmacs.el#15]
I cannot find the VODs on youtube. Where are they?

**Comment by ForNeVeR** [comment]
Moreover, this link says the video has been deleted: https://www.youtube.com/watch?v=-G-o98WKFP4

**Comment by rexim** [comment]
Thanks for the question!

First, I've made all the videos link protected, that means only one who has the link can watch them.

Second, looks like your link is wrong. Here the recording of two previous episodes:
- http://www.youtube.com/watch?v=8oLKDH2gw2g
- http://www.youtube.com/watch?v=Yfk7eh0azc0

Third, I'm ok with the video archive but I'm a little shy about the videos and don't want to make all the videos public or put the list of them to a too public place like README. Can you suggest a good place?

**Comment by ForNeVeR** [comment]
You could add a place to your program that will generate the links to the videos. So only guys who have emacs and are really willing to could get the videos :)

**Comment by rexim** [comment]
Hah, nice idea! Thanks! I'll think about it. :)

**Comment by Minoru** [comment]
> don't want to make all the videos public or put the list of them to a too public place like README

Just a reminder: this issue is public, and you posted the links here.

**Comment by rexim** [comment]
> too public

This issue is not public enough. :)

**Comment by ForNeVeR** [comment]
And he posted only two links. I hope in future there will be more, but I don't think we'll post them all here.

**Comment by rexim** [comment]
Here is the third video http://www.youtube.com/watch?v=LyFeiSI2pB4

Before the next stream I'll prepare a good place for keeping the video archive.

**Comment by rexim** [comment]
I actually have another idea on this. I've created a link protected playlist. And I'm gonna put all the videos there: https://www.youtube.com/playlist?list=PLiOAioBxutV6QXPjBczSu7Xb_5kj-3KYA
