### ISSUE TITLE
Distances instead of directions in the track board.

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#159]
See https://github.com/codingteam/pacmacs.el/issues/153#issuecomment-156943987 for more info

**Comment by Minoru** [comment]
But on the stream, you told me you consider dumbness of line distance to be a game mechanic =\

**Comment by rexim** [comment]
Exactly! It's a game mechanic until this issue is resolved. :)

Sorry, if I was not clear. Basically, on the stream I wanted something that simply works. BFS distance approach is good, but requires too many changes. Enough for a separate issue. My point was not to do this on the stream, because we were working on completely different issue. So "game mechanic" is basically an excuse for not doing that on the stream. :)

**Comment by rexim** [comment]
Furthermore, nobody says to implement this right now. So the dumb approach will be there for a while. And maybe during the implementation we will discover that the dumb approach is funnier than the smart one, and will decline this issue completely. Who knows. :)

**Comment by rexim** [comment]
So, it is good to have this ticket anyway

**Comment by rexim** [comment]
All the commits above this comment are related to #163 I just used wrong issue number during the development and noticed that too late to fix anything...
