### ISSUE TITLE
More maps with big pills and terrified ghosts

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#162]
We need more maps that involve #81 and #153 

Since Mr @ForNeVeR is really experienced game level designer, I'm assigning this task to him.

**Comment by rexim** [comment]
We already have big pills and terrified ghost for quite awhile. But those things are not visible, because they are not used anywhere. So I would like to resolve this issue as soon as possible.

@ForNeVeR don't you mind if I assign this issue to myself and plan it for the next stream?

**Comment by ForNeVeR** [comment]
I don't mind.

**Comment by rexim** [comment]
@ForNeVeR =*
