### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#28]
cc @ForNeVeR @Minoru @ttldtor @IngvarJackal @Newlifer

What license should we distribute this game under? I'm ok with MIT.

**Comment by rexim** [comment]
Btw, I've already put MIT to the pacman.el file :D

**Comment by rexim** [comment]
But we can change if it's not ok for someone.

**Comment by ForNeVeR** [comment]
Personally I like MIT very much and prefer it for any purposes.

**Comment by Minoru** [comment]
I'm okay with MIT for code, but not sure if it's suitable for artistic work. Maybe you should license your sprites under [CC-BY](https://creativecommons.org/licenses/by/4.0/)?

**Comment by rexim** [comment]
@Minoru oh, thank you for reminding me about the sprites! I'm ok with CC-BY for them, especially after #11 <.<

**Comment by Minoru** [comment]
You might also blog about the sprites so that others can take advantage of your work. I doubt we're the only people who Googled for freely available Pac-Man sprites.

**Comment by rexim** [comment]
@Minoru you are so awesome! Thank you! =3
