### ISSUE TITLE
Refactor before the stream

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#43]
cc @ForNeVeR @Minoru @ttldtor @IngvarJackal @Newlifer

What is better? Refactor the code on the stream (create specific tasks for it and plan them for the Tsoding milestones) or refactor before the stream (plan for the PreTsoding millestones).

I would go with PreTsoding. I think refactored code will help us to move faster on the streams and I'm not sure if refactoring is even a really interesting thing to watch.

What do you guys think?

**Comment by IngvarJackal** [comment]
Agree with you.

**Comment by Minoru** [comment]
On Fri, Sep 11, 2015 at 11:23:56AM -0700, Alexey Kutepov wrote:

> I'm not sure if refactoring is really interesting thing to watch.

It could be interesting if the code was real messy or the intended
refactoring was complex. But it's not your case, so I vote for PreTsoding
(i.e. refactoring before the stream).

## 

Regards,
Alexander Batischev

**Comment by rexim** [comment]
> It could be interesting if the code was real messy or the intended refactoring was complex.

Hm... I don't actually mind to do complex refactorings on the streams. You know, with drawing on the board and detailed explanation why the new approach is better than the old one... Ok, a good point actually. During the planning I'll try to see if the refactoring will be interesting and will plan it accordingly. Thanks.
