### ISSUE TITLE
Document supported image format limitation

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#45]
Pacman.el's sprites are stored in the png format. So if the user's Emacs doesn't have support for png the game won't work.

Emacs for Windows from the [official GNU repository](ftp://ftp.gnu.org/gnu/emacs/windows/) doesn't support png out of the box. But there is a workaround for that: http://stackoverflow.com/questions/2650041/emacs-under-windows-and-png-files We should document that workaround as well.

**Comment by rexim** [comment]
Maybe we can switch to XPM as the default format? I mean it doesn't change almost anything from the source code perspective (we only have to tweak [this thing](https://github.com/rexim/pacman.el/blob/master/pacman-resources.el#L37)) and it's really easy to convert png to xpm with ImageMagick, but this will make the game work on the official Windows Emacs build out of the box without any workarounds, because the build is already shipped with `libXpm.dll`.

@ForNeVeR, I really want to know your opinion on this, since we've recently discussed this problem in the chat. Thanks!

**Comment by ForNeVeR** [comment]
Well, I think that if we can support Windows emacs without _much_ fucking up our build process - then we should do that. Whether or not to count XPM conversion as _much_ is up to you. Personally I am okay with that.

**Comment by rexim** [comment]
Thank you uncle @ForNeVeR for your wisdom!
