### ISSUE TITLE
Walls are not shown on Windows

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#59]
Windows 8.1
Emacs 24.5.1
Pacman.el 05e30ca

**Comment by rexim** [comment]
Looks like there is a discrepancy between how the `pacman-create-color-block` function works on Windows and on Linux

**Comment by rexim** [comment]
Looks like we didn't capture that. The root cause of the bug is that for Linux in xbm `1` means **foreground** color, `0` means **background**. But for Emacs on Windows for some reason the behavior is swapped. That is `1` means **background** and `0` means **foreground**.

That's why we introduced that workaround with setting the same color for both foreground and background. But this workaround prevents us from easy implementation of #131

Maybe we have to do something with it, 'cause I don't wanna draw those sprites manually. :)

**Comment by rexim** [comment]
@ForNeVeR btw, could you please checkout `f7b17f7~1` and check if the bug is reproducible on your environment?

**Comment by ForNeVeR** [comment]
I think that the bug is reproducible for me in the mentioned commit. In it I cannot see any walls at all.
