### ISSUE TITLE
Rename the game

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#66]
Someone already created `pacman.el`: http://www.emacswiki.org/emacs/PacmanMode

I think we need to rename the project to avoid confusion. How about `Pacmacs`?

**Comment by Newlifer** [comment]
+

**Comment by rexim** [comment]
@Newlifer thanks for the vote! :)

**Comment by rexim** [comment]
Some useful information on repo renaming https://help.github.com/articles/renaming-a-repository/

**Comment by rexim** [comment]
I like the comments by http://www.emacswiki.org/emacs/PacmanMode

> I was hoping for a new game written in Emacs Lisp… :’( – AlexSchroeder

I think we have good news for AlexSchroeder :)

**Comment by rexim** [comment]
Oh, I believe AlexSchroeder is @kensanata :)

**Comment by ForNeVeR** [comment]
I don't think that's good idea to mess pacman-the-package-manager and pacman-the-game. Package manager is more important IMO, so we have to rename our pacman-the-game.el to something else.

**Comment by ForNeVeR** [comment]
And oh yes, `Pacmacs` seems nice to me.

**Comment by rexim** [comment]
@ForNeVeR thanks! :)

**Comment by Minoru** [comment]
On Thu, Oct 01, 2015 at 12:34:25AM -0700, Alexey Kutepov wrote:

> I think we need to rename the project to avoid confusion. How about `Pacmacs`?

Sounds nice and creative; I vote for it.

## 

Regards,
Alexander Batischev

**Comment by rexim** [comment]
Thank you mr @Minoru =3
