### ISSUE TITLE
The hitting ghost should be visible in the death state

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#78]
Currently it's placed behind the pacman and we cannot see it

**Comment by ForNeVeR** [comment]
Maybe you could apply some triumphing animation to it.

**Comment by rexim** [comment]
@ForNeVeR it's actually a nice idea! But it should be a separate ticket and, of course, be implemented after fixing this bug because otherwise we won't even see that triumphing animation. :)

**Comment by rexim** [comment]
Needed for #93
