### ISSUE TITLE
Tunneling effect with Pacman and Ghost collision

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#88]
I still experience it sometimes. We need to fix that somehow.

**Comment by rexim** [comment]
I think it may happen when two object that are close to each other (neighbor cells) make a step in the opposite directions toward each other simultaneously.

The situation may look like this for two objects with the same speed:

```
|1>|  |  |<2|

|  |1>|<2|  |

|  |<2|1>|  |
```

For objects with different speeds the situations is more complex but the tunneling effect is still possible.

We could try to do the following algorithm:
1. Make a step with pacman
2. Check for collision
3. Make a step with ghosts

**Comment by rexim** [comment]
Yeah, and when we detect the collision we have to switch to the death state without making the step for the ghosts.

**Comment by ForNeVeR** [comment]
I believe that the situation you describe here would be impossible in the original pacman.

It is not completely tile-based, and character movement can be controlled more precisely. So pacman would be killed immediately after it tries to move towards the ghost.

The proper image should be

```
|1>|  |  |<2|

|  |1>|<2|  |

|  |<2|  |  |
```

(assuming pacman tried to move towards the ghost and died, and the ghost moved to the former pacman position)

Maybe you could stop the game at stage `|  |x>|<2|  |` (where `x>` is dead pacman) to show the death animation properly without disappearing ghost.

**Comment by rexim** [comment]
> I believe that the situation you describe here would be impossible in the original pacman.
> 
> It is not completely tile-based, and character movement can be controlled more precisely. So pacman would be killed immediately after it tries to move towards the ghost.

Thank you for pointing that out. I think I should have say that in the description of the issue. But let's leave this information in your comment. :)

And the image

```
|1>|  |  |<2|

|  |1>|<2|  |

|  |<2|  |  |
```

is exactly the thing I wanted to achieve by changing the order of steps and checks, thanks!

> Maybe you could stop the game at stage `| |x>|<2| |` (where `x>` is dead pacman) to show the death animation properly without disappearing ghost.

And here you're describing a different issue #78. But yeah, maybe it could be fixed in the scope of this one, thanks!

**Comment by rexim** [comment]
One colleague of mine just suggested to not fix that and leave it as a feature. :)
