### ISSUE TITLE
Use one image inside of Emacs buffer as a canvas

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#9]
We need to investigate if it's possible to do so

**Comment by rexim** [comment]
Yes! It is fucking possible! Via xpm!

![](http://i.imgur.com/n8Qrhkr.png)

@ForNeVeR, @Minoru, guys! You gotta check this out! We can use one image as a canvas for the whole game!

**Comment by rexim** [comment]
But I don't know what to do with this knowledge. Because using this technique in our game will require a lot of rewriting. :(

**Comment by rexim** [comment]
Also we need to check how smooth the animation will be with this technique.

**Comment by Minoru** [comment]
What's wrong with sprites approach? Why this one is better? I'm
confused.

## 

Regards,
Alexander Batischev

**Comment by rexim** [comment]
I understand your confusion. Let me explain everything once I'm home. :)
07.09.2015 16:39 пользователь "Alexander Batischev" <
notifications@github.com> написал:

**Comment by rexim** [comment]
We've already discussed this with @Minoru in the chat. A little bit later I'll put the notes of that conversation here.

**Comment by rexim** [comment]
In our current approach we insert `N x M` images into the buffer on each game tick. It's a pretty good approach but it has its own limitations. For example game objects can move only discretely from on cell to another. I suggest another approach where we use only one image inside of an Emacs buffer as a canvas. It gives as pixel level control over the game's frame. With this control we can implement really smooth transitions. Here is how it will look: http://www.youtube.com/watch?v=lab6cpT3HhA

**Comment by rexim** [comment]
But I'm not going to implement this in the 5th Tsoding. Such thing has to be properly planned. On the 5th Tsoding I'll focus on #32

**Comment by rexim** [comment]
All the source code that I used in the video above I've put to the [one-image-canvas](https://github.com/rexim/pacman.el/tree/one-image-canvas) branch. Fill free to play with it if you want. :)

**Comment by rexim** [comment]
Since we know this technique is possible I close the issue.

**Comment by rexim** [comment]
Checked this stuff on Windows 8.1, Emacs 24.5. Works good too and consumes even less CPU than on my Ubuntu (25% vs 30%)
